name: Release Production

on:
  push:
    tags-ignore:
      - "dev-*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tar archive
        run: |
          tar -cvf AutoBees.tar --exclude-from=.tarignore *

      - name: Create release with the archive
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: AutoBees.tar
